Added a new theme and some detail
gitroll-dev/gitroll-profile-card pull request #1
Opened 2024-11-21 06:04 UTC by rahulpanchal0106

Hey!

I've added a cozy dark theme called "midnight". 
Tried to make the final card div a bit rounded for better aesthetic, shown just like in the "Deploy GitRoll badge on GitHub" preview page.

2024-11-21 16:41 UTC, 1chooo commented on src/theme.ts
> -  nord,
It looks like the Midnight theme was successfully added, but the Nord theme was removed on this line. You may need to add it back.

2024-11-21 16:45 UTC, 1chooo reviewed
Could you provide the screenshot of execution results, such as the differences before and after?

2024-11-21 16:53 UTC, 1chooo requested changes

2024-11-21 16:53 UTC, 1chooo commented on src/theme.ts
> +  nord
The comma (`,`) is missing at the end of `nord`.

2024-11-22 10:02 UTC, rahulpanchal0106 commented
> Could you provide the screenshot of execution results, such as the differences before and after?

Its like a mix of Dark theme, and TokyoNight theme.
Here's how the existing themes look:

- Dark Theme:
![image](https://github.com/user-attachments/assets/27856a95-55c7-4387-8332-280f6071b5f4)

- TokyoNight theme:

![image](https://github.com/user-attachments/assets/086b02e8-5307-43e4-b000-eb68d7389f5d)

- And the new MidNight Theme,
![image](https://github.com/user-attachments/assets/51390c29-fbb4-449e-841e-91d6db041657)



Apologies for the delayed response, I’ve been caught up with exams. Thank you for your patience! :)

2024-11-22 12:31 UTC, JacobLinCool approved these changes
LGTM!

2024-11-22 12:39 UTC, 1chooo approved these changes
LGTM!

2024-11-22 16:06 UTC, merged